### ISSUE TITLE
ein oder mehrere Zeichen eines generierten Passworts können leer sein

### ISSUE THREAD

**Issue by otsmr** [Johannes-Schiel/password-generator#2]
Habe einen kleinen Bug in der PasswordGenerator-Klasse gefunden :D
Es kann vorkommen, dass ein oder mehrere Zeichen eines generierten Passworts leer sind. 

Dies ist der Fall, wenn das Ergebnis von [Zeile 7](https://github.com/Johannes-Schiel/password-generator/blob/master/src/js/generatepassword.js#L7) gleich 1 ist, bzw. der Zufallswert 0xFF.
```js
res[i] = array[i] / 0xFF; // -> res[i] = 1
```

Denn dann wird von der Funktion charAt in [Zeile 18](https://github.com/Johannes-Schiel/password-generator/blob/master/src/js/generatepassword.js#L18) ein leerer String zurückgegeben, da ([MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charAt)):
> The index of the first character is 0, and the index of the last character in a string called stringName is stringName.length - 1. If the index you supply is out of this range, JavaScript returns an empty string.
```js
characters.charAt(Math.floor(randomness[i] * charactersLength)) // -> charAt(1 * charactersLength)
```
Ein möglicher Lösungsansatz wäre: 
```js
characters.charAt(Math.floor(randomness[i] * charactersLength - 0.000001));
```
![Screenshot](https://user-images.githubusercontent.com/48922451/114446378-75b1f880-9bd1-11eb-963f-af7a038c8a75.png)

**Comment by Keven6077** [comment]
Bei diesem Lösungsansatz hätte man doch das Problem, wenn jetzt im `randomness` Array eine `0` steht.
Weil man somit einen negativen Index hat (out of range) und wieder einen leerer String zurückbekommt.

Die einfachste Lösung wäre, wenn `0xFF` mit `0xFE` ersetzt wird. Da dieser Fall selten vorkommt, dürfte es auch der "rendomness" keinen Abbruch tun, also in [Zeile 7](https://github.com/Johannes-Schiel/password-generator/blob/bba6b22015f3089df5503b01fbac6febf949a036/src/js/generatepassword.js#L7) einen if Block hinzufügt:

~~~java        
for (let i = 0; i < array.length; i++) {
    if(res[i] == 0xFF) {
        res[i] = 0xFE;
    }
    res[i] = array[i] / 0xFF;
}
~~~

**Comment by otsmr** [comment]
Stimmt!
Du musst noch `res[i]` mit `array[i]` ersetzen, aber ansonsten würde ich dir da zustimmen, dass es von der "randomness" her ok ist :D.
```js
for (let i = 0; i < array.length; i++) {
    if(array[i] == 0xFF) {
        array[i] = 0xFE;
    }
    res[i] = array[i] / 0xFF;
}
```

**Comment by Keven6077** [comment]
Ja jetzt passts, habe mich im Array vertan 🤦‍♂️.

**Comment by Johannes-Schiel** [comment]
@TheMorpheus407 denke hier müsstest du was zu sagen :)

**Comment by TheMorpheus407** [comment]
Fixed in [https://github.com/Johannes-Schiel/password-generator/commit/1cd9cf5defe93914b28f60a0281ebfa7d3173f1e](url)
